EMAILS_DEMO = [
    {"id": 1, "asunto": "Factura nº 2026-45 pendiente de pago",
     "remitente": "proveedor@suministros.com",
     "cuerpo": "Buenos días. Le recordamos que la factura 2026-45 emitida el 3 de junio sigue pendiente de pago. Adjuntamos nuevamente el documento. Gracias."},
    {"id": 2, "asunto": "¡Oportunidad! 50% de descuento en tu seguro",
     "remitente": "ofertas@segurosrapidos.com",
     "cuerpo": "Hola. Solo esta semana, aprovecha un 50% de descuento en la renovación de tu seguro de responsabilidad civil. ¡No dejes pasar esta oferta!"},
    {"id": 3, "asunto": "¿Puedes confirmar la reunión de mañana?",
     "remitente": "cliente@estudioarquitectura.es",
     "cuerpo": "Hola, Laura. ¿Tienes un momento para revisar los planos? Por favor, confirma si te viene bien la reunión de mañana a las 10:00."},
    {"id": 4, "asunto": "Envío de documentación trimestral IVA",
     "remitente": "gestoria@contable.es",
     "cuerpo": "Estimada Laura, te hago llegar el resumen de la factura de gastos del trimestre para que podamos presentar el IVA a tiempo. Saludos."},
    {"id": 5, "asunto": "Tu suscripción de Office caduca pronto",
     "remitente": "soporte@microsoft.com",
     "cuerpo": "Tu suscripción actual a Microsoft 365 caduca el próximo 30 de junio. Realiza la renovación para no perder el acceso a tus archivos."},
    {"id": 6, "asunto": "Propuesta colaboración: Software Gestión",
     "remitente": "ventas@soft-tools.com",
     "cuerpo": "Buenos días. Somos una empresa de software y tenemos una propuesta de colaboración para tu actividad administrativa. ¿Estarías interesada en una demo?"},
    {"id": 7, "asunto": "¿Nos vemos el jueves para el presupuesto?",
     "remitente": "info@reformasgalicia.es",
     "cuerpo": "Hola, Laura. Estamos cerrando los números y necesitamos que valides el presupuesto final. ¿Nos vemos el jueves para revisarlo?"},
    {"id": 8, "asunto": "Notificación: Requerimiento de Hacienda",
     "remitente": "notificaciones@aeat.es",
     "cuerpo": "Se ha publicado una notificación electrónica en su buzón de Hacienda. Es necesario que acceda al portal para revisar el requerimiento."},
    {"id": 9, "asunto": "Re: Solicitud de factura rectificativa",
     "remitente": "administracion@empresa.com",
     "cuerpo": "Laura, en respuesta a tu petición, te adjunto la factura rectificativa corregida según los datos que nos facilitaste."},
    {"id": 10, "asunto": "Financiación y créditos para pymes",
     "remitente": "banco@banca-digital.com",
     "cuerpo": "Descubre nuestras nuevas líneas de crédito con un descuento especial en las comisiones de apertura para autónomos. Consulta nuestras condiciones."},
    {"id": 11, "asunto": "¿Recibiste el archivo?",
     "remitente": "cliente@diseno.com",
     "cuerpo": "Hola. Por favor, confirma si recibiste el archivo con el logo que te envié ayer. Quedo a la espera."},
    {"id": 12, "asunto": "Recordatorio: Factura vencida el día 10",
     "remitente": "cobros@suministros.com",
     "cuerpo": "Te informamos que la factura del mes pasado estaba vencida el día 10. Por favor, revisa el estado del pago en tu banco."},
    {"id": 13, "asunto": "Informe de actividad mensual",
     "remitente": "gerencia@empresa-z.com",
     "cuerpo": "Buenos días, Laura. Adjunto el informe de actividad mensual. Por favor, agrégalo al expediente administrativo correspondiente."},
    {"id": 14, "asunto": "¡Liquidación total de material de oficina!",
     "remitente": "papeleria@tiendaonline.com",
     "cuerpo": "¡Grandes noticias! Tenemos una liquidación con hasta 70% de descuento en todo nuestro stock de papelería y mobiliario de oficina."},
    {"id": 15, "asunto": "Respuesta necesaria: Firma de contrato",
     "remitente": "legal@asesoria.es",
     "cuerpo": "Es necesaria tu intervención para completar la firma del nuevo contrato de colaboración. Adjuntamos el documento para que procedas."},
    {"id": 16, "asunto": "Consulta sobre honorarios profesionales",
     "remitente": "potencial.cliente@gmail.com",
     "cuerpo": "Hola, Laura. Me han recomendado tu trabajo y me gustaría saber cuáles son tus honorarios por una gestión administrativa integral."},
    {"id": 17, "asunto": "Factura de luz - Periodo Mayo/Junio",
     "remitente": "facturacion@eléctrica.es",
     "cuerpo": "Ya tienes disponible tu factura de consumo eléctrico del periodo mayo-junio en nuestra área de clientes."},
    {"id": 18, "asunto": "Newsletter: Novedades laborales 2026",
     "remitente": "noticias@laboral.es",
     "cuerpo": "Lee nuestra última newsletter sobre los cambios en la normativa laboral que afectan a los trabajadores autónomos en 2026."},
    {"id": 19, "asunto": "¿Puedes confirmar disponibilidad hoy?",
     "remitente": "socio@colaborador.es",
     "cuerpo": "Hola, ¿puedes confirmar disponibilidad para una llamada rápida hoy a las 17:00? Tenemos un asunto urgente que tratar."},
    {"id": 20, "asunto": "Aviso urgente: Problema acceso portal",
     "remitente": "tecnico@it-services.com",
     "cuerpo": "Se ha detectado un aviso urgente sobre la caída del servidor donde alojas tus datos. Estamos trabajando en ello, rogamos paciencia."},
    {"id": 21, "asunto": "Envío presupuesto solicitado",
     "remitente": "laura@tudominio.com",
     "cuerpo": "Hola. Tal como acordamos, te envío el presupuesto para la gestión administrativa solicitada. Quedo a la espera de tus noticias."},
    {"id": 22, "asunto": "Factura proveedor de internet",
     "remitente": "atencion@telecom.com",
     "cuerpo": "Estimado cliente, ya está disponible la factura mensual de tus servicios de fibra y telefonía. Puedes verla en el portal web."},
    {"id": 23, "asunto": "Invitación a webinar de contabilidad",
     "remitente": "eventos@asociacion.es",
     "cuerpo": "Te invitamos a un webinar gratuito sobre optimización de contabilidad para autónomos que realizaremos el próximo miércoles."},
    {"id": 24, "asunto": "Error crítico en envío de nómina",
     "remitente": "personal@empresa-x.com",
     "cuerpo": "Se ha detectado un error crítico en el fichero de nóminas enviado esta mañana. Por favor, detén el procesamiento inmediatamente."},
    {"id": 25, "asunto": "¿Podrías confirmar la recepción del pago?",
     "remitente": "proveedor@materiales.com",
     "cuerpo": "Hola, Laura. Hemos realizado la transferencia de la factura pendiente. ¿Podrías confirmar la recepción del pago cuando se refleje en tu cuenta?"},
]
